---
services:
  app:
    env_file: ".env"
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: development
    volumes:
      - ./src:/app/:ro
    depends_on:
      - postgres
      - redis
  nginx:
    env_file: ".env"
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
  postgres:
    env_file: ".env"
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    volumes:
      - postgresql-db:/var/lib/postgresql/data
  redis:
    env_file: ".env"
    read_only: true
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
    command: >
      redis-server --bind 0.0.0.0 --appendonly no --save --protected-mode yes

volumes:
  postgresql-db:
    external: false
