---
name: docker -- build-image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  packages: write
  attestations: write
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [app, nginx, postgres, redis]
    name: docker-build
    steps:
      - name: git -- checkout
        uses: actions/checkout@v3

      - name: docker -- login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker -- setup-qemu
        uses: docker/setup-qemu-action@v3

      - name: docker -- setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: docker -- build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/${{ matrix.image }}/Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ matrix.image }}-${{ github.sha }}
          push: true
