---
name: docker -- build-image

on:
  pull_request:
    branches: ['main']

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [app, nginx, postgres, redis]
    name: docker-build
    steps:
      - name: git -- checkout
        uses: actions/checkout@v3

      - name: docker -- setup-qemu
        uses: docker/setup-qemu-action@v3

      - name: docker -- setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: docker -- build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/${{ matrix.image }}/Dockerfile
